micronaut:
  application:
    name: micronautjpa
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
datasources:
  default:
    dialect: H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: